### ISSUE TITLE
interaction of learning material

### ISSUE THREAD

**Issue by lorenzwalthert** [jonmcalder/swirl-courses#3]
The power of regular expression really seems to be to combine different meta characters. So I think think the Intro and the Anchor lesson are fine, but then, e.g. when introducing character classes, why not adding a final question where we want to match digits at the beginning of a string, that is combining `^` with `[:digit:]`?
We could even make this a general rule for subsequent lessons: All lessons have two parts: Part 1 introduces a new concept whereas Part 2 requires combining the newly acquired knowledge with all the content of previous lessons.

**Comment by jonmcalder** [comment]
Yes I am totally with you on this. I actually had a similar thought, but had envisioned introducing all the concepts separately and somewhat succinctly upfront and then making the material more advanced later on in the course i.e. having lessons towards the end that mix all the concepts together for more practical/realistic regex scenarios. But it might be better to build things up gradually as you suggest by combining new techniques with previously learnt ones as you go.

**Comment by lorenzwalthert** [comment]
Well the question is also whether you want the lessons to be self-contained (in the sense of independent) or not. I think it's not absolutely necessary since we are not building an encyclopedia... I also feel it's better to not have too many short sessions. But it's up to you...

**Comment by jonmcalder** [comment]
Yeah I have been wondering what kind of lesson length to aim for. I do think what you are suggesting (iterative linking) is probably the better way of going since the linking of different building blocks in regex is crucial to getting a better handle on the specifics of how each of these things can work in the context of other tools.

**Comment by jonmcalder** [comment]
The main downside I see for linking together concepts learned in previous lessons is that it discourages 'drop-in' lessons e.g. to refresh your understanding of a particular topic or try a few practice examples. My sense is that this is almost certainly not the primary use case for swirl content (i.e. it should be aimed at newer R users or at least R users who are relatively new to the topic area being taught). But that doesn't mean that one shouldn't try and make lessons which make good, focused reference material for a particular topic. Having separate lessons (part 1, part 2) then is probably the best way to get the best of both worlds i.e. for the introduction of a topic/concept and then for mixed questions on the topic/concept

**Comment by jonmcalder** [comment]
I've been thinking through this some more and have come around. Given the low chance of this kind of lesson content being used as 'reference' material, and the fact that it is essential to learn to link different concepts together in order to get a firm grasp on regular expressions I'm gonna go with the iterative linking approach. Thanks again for the feedback!
